### PR TITLE
Use Value =:= #{} to check empty map

### PR DESCRIPTION
**Pull request by williamthome**
This PR uses `=:= #{}` instead of `maps:to_list/1` to check if the map is empty.

### Empty map

```console
./erlperf 'maps:to_list(#{}) =:= [].' '#{} =:= #{}.'
Code                              ||        QPS       Time   Rel
#{} =:= #{}.                       1   75367 Ki      13 ns  100%
maps:to_list(#{}) =:= [].          1   33972 Ki      29 ns   45%
```

### Map with values
```console
./erlperf 'maps:to_list(#{a=>a,b=>b,c=>c,d=>d,e=>e}) =:= [].' '#{a=>a,b=>b,c=>c,d=>d,e=>e} =:= #{}.'
Code                                              ||        QPS       Time   Rel
#{a=>a,b=>b,c=>c,d=>d,e=>e} =:= #{}.               1   75467 Ki      13 ns  100%
maps:to_list(#{a=>a,b=>b,c=>c,d=>d,e=>e})          1   17553 Ki      56 ns   23%
```

> **Note**
> This PR can be closed if #28 would be accepted.

### CODE REVIEW

**Comment by michalmuskala** [comment]
It's even faster to have a guard `when Map =:= #{}` than checking the size.

However, you'll need to take into account that for non-empty map this version will be slower, since you'll add the extra check

**Comment by williamthome** [comment]
Thanks, @michalmuskala! I've updated the PR.

**Comment by lpil** [comment]
For me this change is benchmarking as being slightly slower, which would make sense to me as there is an additional check for each map being encoded. Do you get different results from the benchmark?

**Comment by williamthome** [comment]
I'm not sure, but maybe there is no empty `map/object` in the JSONs used for tests, and then the results are almost the same.
The check implemented in this PR is faster. You can see this in the benchmarks in the PR description.

**Comment by williamthome** [comment]
A slight difference, but I think there is no difference due to what I said above.

## Better

image

image

image

image

image

image

## Worst

image

image

**Comment by lpil** [comment]
I've run them again and I'm again getting no improvement. All either the same or slower.

**Comment by williamthome** [comment]
~~I don't see a reason to be slower. Any idea @michalmuskala?~~
Sorry, the check is an extra step. That's the reason.

**Comment by williamthome** [comment]
Well, we can consider empty objects rare and forget this extra step to check empty maps.
What do you think? If yes, this PR can be closed.

**Pull request closed without merging**
