### PR TITLE
Support encoding input strings in latin1 (ISO-8859-1)

### PR DESCRIPTION
**Pull request by lukebakken**
Add test to demonstrate failure with latin1 encoding

Related to rabbitmq/rabbitmq-server#5551

### CODE REVIEW

**Comment by lukebakken** [comment]
@lpil I'm not sure if you're interested in this edge-case, but I ran into it while testing RabbitMQ on Windows, where the data directory being used has `latin1` character `233` (accented e) in it.

**Comment by lukebakken** [comment]
@michaelklishin and @dumbbell may have opinions on this!

**Comment by michaelklishin** [comment]
I have run the encoding benchmark just in case and observed *no* significant difference 👍

**Comment by michalmuskala** [comment]
FWIW, per the JSON spec, JSON is only allowed to be encoded in utf8

**Comment by lukebakken** [comment]
@michaelklishin I'm assuming you meant "no significant difference" 😄 There would only be a difference if a significant number of input strings triggered the `invalid_byte` error and could then be converted to `utf-8`.

@michalmuskala sorry the PR title could have been better. This allows input strings that happen to be `latin1`-encoded to still work. The output JSON is always `utf-8`. It does "hide" this fact from the user so maybe it's better to error with `invalid_byte`.

We have a fix in RabbitMQ so feel free to close this if you'd not like to support this edge case.

**Comment by michaelklishin** [comment]
Yup, I observed no significant difference, sorry about the confusion :)

**Comment by lukebakken** [comment]
OK after thinking about this and working a bit more on rabbitmq/rabbitmq-server#5551 it does seem best for this library to `error` when invalid data is found rather than fixing it behind the scenes.

**Comment by lpil** [comment]
Thanks everyone for figuring this out while I was on my little holiday :)

**Pull request closed without merging**
