### PR TITLE
(feat) Add encoders for erlang native types

### PR DESCRIPTION
**Pull request by leonardb**
Types:
- datetime (assumes all timestamps are UTC to produce ISO 8601 format timestamps)
- date
- ipv4/6

IPv4/6 CIDR formats as well

### CODE REVIEW

**Comment by williamthome** [comment]
@lpil a friendly reminder to you to take a look at this nice feature :)

**Comment by eproxus** [comment]
I like the idea, but the risk is that this encoding is too liberal. E.g. if you have a `-record(user, {id, name, email})` that you include in your data (by "mistake" because you haven't encoded it yourself yet) it would raise a `{invalid_ip, {user, 123, <<"foo">>, <<"bar">>}}` error.

Perhaps a better way would be a custom encoding function that is called if there's no match in the default encoding type set?

JSON itself _does not_ define a timestamp format so this doesn't really belong in the encoder.

**Comment by leonardb** [comment]
@eproxus I've added fairly strict guards to try and eliminate the issue you've raised and hopefully you'll reconsider.

The reason I added the PR is that it's often the case we're returning the result of a DB query while shipping that data off to another process as well. I'd be a much smoother experience for us to just let the encoder handle the conversion.

Passing random tuples as per your example into thaos:encode should just yield a function clause error exactly like before. eg
```
1> thoas:encode(#{<<"record">> => {user, <<"Dave">>, <<"Jones">>, 27}}).
** exception error: no function clause matching thoas_encode:value({user,<<"Dave">>,<<"Jones">>,27},
                                                                   #Fun<thoas_encode.0.37105625>) (/opt/thoas/src/thoas_encode.erl, line 1720)
     in function  thoas_encode:map_naive/2 (/opt/thoas/src/thoas_encode.erl, line 1703)
     in call from thoas:encode/2 (/opt/thoas/src/thoas.erl, line 99)
```

**Comment by lpil** [comment]
Hello! Think the IP address ones are too niche and specific for this library. Could you remove these please? If the user wants to encode IP addresses they can do this manually.

**Comment by leonardb** [comment]
@lpil Would you be averse to adding an encoder extension mechanism?

For example, as part of opts for encode
```
#{escape => json,
   encoders => #{
     date => {encode_date, encode},
     datetime => {encode_datetime, encode},
     inet => {Mod, Fun},
     .... whatever other native erlang types that can be supported via basic 'shape' matching in function heads
   }
}
```

This would obviously require that the head patterns ~and guards~ remain in place, but the default behavior would be to just error out if no encoder for the type is configured, which is the existing behavior.

The encoders for date and datetime could be moved to modules (as above) within Thoas and have defaults set.

The existing encode function would be extended to carry the Encoders option and we'd end with something like
```erlang
value({_Y, _M, _D} = Date, Escape, #{date := {Mod, Fun}} = Encoders) ->
    case Mod:Fun(Date) of
        {ok, DateStr} ->
            encode_string(DateStr, Escape, Encoders);
        _ ->
            encode_string(Date, Escape, Encoders)
    end;
value({{_Y, _M, _D}, {_Hr, _Min, _Sec}} = Datetime, Escape, #{datetime := {Mod, Fun}} = Encoders) ->
    case Mod:Fun(Datetime) of
        {ok, DatetimeStr} ->
            encode_string(DatetimeStr, Escape, Encoders);
        _ ->
            encode_string(Datetime, Escape, Encoders)
    end;
...
```

**Comment by lpil** [comment]
No support for inets types please, thank you.

**Comment by leonardb** [comment]
Will close this PR and open a new PR with only support for date/datetime
See: https://github.com/lpil/thoas/pull/26

**Comment by williamthome** [comment]
> #{escape => json,
>    encoders => #{
>      date => {encode_date, encode},
>      datetime => {encode_datetime, encode},
>      inet => {Mod, Fun},
>      .... whatever other native erlang types that can be supported via basic 'shape' matching in function heads
>    }
> }

I really enjoyed the encoder mechanism.

**Comment by leonardb** [comment]
> > #{escape => json,
> > encoders => #{
> > date => {encode_date, encode},
> > datetime => {encode_datetime, encode},
> > inet => {Mod, Fun},
> > .... whatever other native erlang types that can be supported via basic 'shape' matching in function heads
> > }
> > }
> 
> I really enjoyed the encoder mechanism.

Thanks. I went ahead and implemented it on this branch for fun.
https://github.com/leonardb/thoas/tree/feat/native-common-type-encodings/src/encoders

**Comment by williamthome** [comment]
Nice, @leonardb!
Just pushed a PR with this idea here #28.

**Comment by eproxus** [comment]
I'm curious, since JSON doesn't define neither date types nor IP addresses, what is the rationale for including one but not the other in the encoder/decoder?

**Comment by leonardb** [comment]
Yes, those 'types' are not defined in the JSON spec, but this is not about
something existing in the specification, it's about making generation of
JSON easier for the Erlang library user.

We're not exclusively working with 'strings' and 'numbers' in Erlang, but
binaries, atoms, lists, proplists, maps, and tuples of various shapes, the
common ones being dates, date-times and ip addresses.

The existing encoder handled binaries, atoms, lists, proplists and maps.
Why not handle the commonly used tuple shapes and make it easier for
library users.

Instead of having to pre-process the other 'types' whenever generating JSON
this would now be handled by the encoder.

**Comment by eproxus** [comment]
I would argue for including _no_ special encoder/decoders, but for supporting an extensible encoding/decoding hook that can be adapted by the user.

It's hard to draw the line of where to include "common" types to automatically encode/decode in a JSON library. One users date is another users two-tuple pair of  `rand:seed()` for example... as such, there is no one-size-fits all solution to encoding/decoding things _not_ in the JSON spec.

**Comment by leonardb** [comment]
I don't disagree, which is why I suggested supporting an extension
mechanism which @williamthome then ran with.  See
https://github.com/lpil/thoas/pull/28

I'm hoping this is accepted and I will happily close
https://github.com/lpil/thoas/pull/26 since I'd be able to specify a fun to
replace the `unknown` encoder to handle all the types/shapes I need to.

The extension supporting custom encoders is cleaner imho.

**Pull request closed without merging**
