### PR TITLE
Small fixes and option for nil/null

### PR DESCRIPTION
**Pull request by leonardb**
- Adds `null_as` option to thaos:decode/2 which defaults to `nil` (which is what I think is used in Gleam)
- Correctly encodes both `null` and `nil` as `null`

### CODE REVIEW

**Comment by lpil** [comment]
Thanks for the PR. I think you are right, it doesn't make so much sense to use the atom `nil` now this is not an Elixir library.

How about we remove `nil` and use a different value always? I could see an argument in favour of the atoms `null` or `undefined`. What do you think?

We probably also want to change this to match

https://github.com/lpil/thoas/blob/9daa30e6b415d6c673214dd7a9c34a8717f6bb9f/src/thoas_encode.erl#L100-L103

**Comment by leonardb** [comment]
I kept nil because of your mention of Gleam. Does Gleam use nil or null (I
don't know)? Iirc, some of the other Jason libs support a configurable
nil/null so they are usable in multiple Beam languages, but this is your
project and I'm good with whatever you decide.

Obviously removing nil support makes for a much smaller PR.

Leonard

**Comment by lpil** [comment]
I think we should drop `nil` as Gleam's decoders can handle any null value, it doesn't have to be `nil`.

Let's use `null` as that's what jsone and JSX do by default.  I think we can mostly just replace any use of `nil` with `null`. Would you like to make that change or shall I?

**Comment by leonardb** [comment]
@lpil reverted a number of the changes so we end up just supporting null.

**Review by lpil — APPROVED** [review]
Brilliant, thank you

**Pull request merged**
